### model
model_name_or_path: /home/lt_08321/hdd/wangweihang/checkpoints/Qwen/Qwen2.5-0.5B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
lora_target: all

### dataset
dataset: finetune_realworld_part1, finetune_realworld_part2, finetune_realworld_part3
template: qwen
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2.5-0.5b/full/sft
logging_steps: 10
plot_loss: true
overwrite_output_dir: true
save_steps: 8000000000

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 8000000000
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true

