### model
# model_name_or_path: bidding_outputs/pretrain_outputs/bidding_pretrain_250112
# model_name_or_path: checkpoints/Qwen/DeepSeek-R1-Distill-Qwen-14B
model_name_or_path: checkpoints/Qwen/Qwen2.5-14B-Instruct
model_max_length: 8192
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: lora
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: finetune_continue_250112, finetune_summary_250112
# dataset: finetune_realworld_250105, finetune_realworld_250227
template: qwen
cutoff_len: 8192
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: bidding_outputs/finetune_outputs/finetune@lora@continue_summary@250228
logging_steps: 1
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true