### model
model_name_or_path: bidding_outputs/pretrain_outputs/qwen_pretrain_241216

### method
stage: pt
do_train: true
finetuning_type: full
<<<<<<< HEAD:bidding_srcipts/bidding_pretrain.yaml
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: pretrain_main_241216, pretrain_rules_250112, pretrain_wudao_3
cutoff_len: 4096
# max_samples: 1000
=======
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: bidding_finetune_realworld_250105
template: qwen
cutoff_len: 8192
max_samples: 1000
>>>>>>> 0b9c7780 (bidding real world):bidding_srcipts/qwen_finetune.yaml
overwrite_cache: true
preprocessing_num_workers: 16

### output
<<<<<<< HEAD:bidding_srcipts/bidding_pretrain.yaml
output_dir: bidding_outputs/pretrain_outputs/bidding_pretrain_240112
logging_steps: 10
=======
output_dir: bidding_outputs/finetune_outputs/qwen_pretrain_finetune_250105
logging_steps: 1
>>>>>>> 0b9c7780 (bidding real world):bidding_srcipts/qwen_finetune.yaml
plot_loss: true
overwrite_output_dir: true

### train
<<<<<<< HEAD:bidding_srcipts/bidding_pretrain.yaml
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
=======
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
>>>>>>> 0b9c7780 (bidding real world):bidding_srcipts/qwen_finetune.yaml
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
