### model
# model_name_or_path: checkpoints/Qwen/Qwen2.5-14B-Instruct
model_name_or_path: checkpoints/Qwen/Qwen2.5-72B-Instruct

### method
stage: pt
do_train: true
finetuning_type: lora
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: pretrain_main_250105, pretrain_rules_250105, pretrain_main_250312
cutoff_len: 8192
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: bidding_outputs/pretrain_outputs/pretrain@72B@lora@250402
logging_steps: 10
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
