### model
model_name_or_path: bidding_outputs/finetune_outputs/finetune@14B@pt@full@R@250314
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
deepspeed: examples/deepspeed/ds_z3_offload_config.json

### dataset
dataset: dpo_realworld_20250306
template: qwen
cutoff_len: 8192
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: bidding_outputs/posttrain_outputs/dpo@14B@pt@full@R@250316
logging_steps: 10
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
save_steps: 20000
ddp_timeout: 180000000